######################## default configuration ####################
baseURL = "https://aspoathletisme-tours.fr/"
languageCode = "fr-fr"
title = "ASPO Athlétisme"
summaryLength = "10"
paginate = 4

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
URL = "css/bootstrap.min.css"
[[params.plugins.css]]
URL = "css/slick.css"
[[params.plugins.css]]
URL = "css/font-awesome.min.css"
[[params.plugins.css]]
URL = "css/animate.min.css"
[[params.plugins.css]]
URL = "css/venobox.css"
[[params.plugins.css]]
URL = "css/main.css"
[[params.plugins.css]]
URL = "css/responsive.css"
[[params.plugins.css]]
URL = "css/pure.min.css"

# JS Plugins
[[params.plugins.js]]
URL = "js/jquery.min.js"
[[params.plugins.js]]
URL = "js/bootstrap.min.js"
[[params.plugins.js]]
URL = "js/slick.min.js"
[[params.plugins.js]]
URL = "js/wow.min.js"
[[params.plugins.js]]
URL = "js/venobox.min.js"
[[params.plugins.js]]
URL = "js/main.js"

############################## navigation ###############################

[[menu.main]]
name = "Accueil"
URL = "hero-area"
weight = 1

[[menu.main]]
name = "Le Club"
URL = "about-us"
weight = 2

[[menu.main]]
name = "Actualités"
URL = "blog"
weight = 3

[[menu.main]]
name = "Adhésion"
URL = "price"
weight = 4

[[menu.main]]
name = "Nous rejoindre"
URL = "subscribe"
weight = 5

#[[menu.main]]
#name = "Contact Us"
#URL = "contact-us"
#weight = 6


#################### default parameters ################################
[params]
logo = "images/logo.png"
# meta data
author = "Themefisher"
description = "Site web du club tourangeau ASPO Athlétisme"
# google analitycs ID
#google_analitycs_id = "Your ID"
# mainSections
main_sections = ["post"]
# copyright
copyright = "Copyright &copy; 2021 Design par [Themefisher](https://themefisher.com) & Développé par [Melua](https://melua.fr)"

# Preloader
[params.preloader]
enable = false
preloader = "" # use .png , .svg or .gif format

################################### Footer ############################
[params.footer]
enable = true
contactInfoTitle = "NOUS <span>CONTACTER</span> "
blogTitle = "DERNIÈRES <span>ACTUALITÉS</span>"
galleryTitle = "GALLERIE <span>PHOTO</span>"
socialTitle = "NOUS <span>SUIVRE</span>"

############################ footer contact item
[[params.footer.contactItem]]
title="WhatsApp"
icon = "fa fa-whatsapp"
content = "Sur demande d'invitation"

[[params.footer.contactItem]]
title="Adresse"
icon = "fa fa-map-marker"
content = "41, rue Grécourt 37000 Tours"

[[params.footer.contactItem]]
title="Courriel"
icon = "fa fa-envelope"
content = "info@aspoathletisme-tours.fr"

######################### footer gallery
[[params.footer.gallery]]
image = "images/photo/ag2019.jpg"

[[params.footer.gallery]]
image = "images/photo/champ-fr-2020-2.jpg"

[[params.footer.gallery]]
image = "images/photo/champ-fr-2020-3.jpg"

[[params.footer.gallery]]
image = "images/photo/champ-fr-2020-4.jpg"

[[params.footer.gallery]]
image = "images/photo/champ-fr-2020-5.jpg"

[[params.footer.gallery]]
image = "images/photo/chinon-2019-1.jpg"

[[params.footer.gallery]]
image = "images/photo/chinon-2019-2.jpg"

[[params.footer.gallery]]
image = "images/photo/chinon-2019-3.jpg"

[[params.footer.gallery]]
image = "images/photo/chinon-2019-4.jpg"

[[params.footer.gallery]]
image = "images/photo/chinon-2019-5.jpg"

[[params.footer.gallery]]
image = "images/photo/medoc-2019-2.jpg"

######################## Social Icon 
[[params.footer.socialLink]]
icon = "facebook"
link = "https://fb.com/aspoathletisme"

[[params.footer.socialLink]]
icon = "twitter"
link = "https://fb.com/aspoathletisme"

[[params.footer.socialLink]]
icon = "dribbble"
link = "https://fb.com/aspoathletisme"

[[params.footer.socialLink]]
icon = "instagram"
link = "https://fb.com/aspoathletisme"